# Generated by Django 3.2.19 on 2023-06-20 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=35)),
                ('cnpj', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=25, verbose_name='Código')),
                ('date', models.DateField(verbose_name='Data de Investimento')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Unitário')),
                ('amount', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('brokerage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Corretagem')),
                ('type', models.CharField(blank=True, choices=[('C', 'Compra'), ('V', 'Venda')], max_length=1, verbose_name='Tipo')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_wallet.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
